apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'tf2-{{ id }}'
  labels:
    app: tf2
    {{ label }}/id: "{{ id }}"
spec:
  selector:
    matchLabels:
      app: tf2
      instance: 'tf2-{{ id }}'
  template:
    metadata:
      labels:
        app: tf2
        instance: 'tf2-{{ id }}'
    spec:
      terminationGracePeriodSeconds: 1
      hostNetwork: true
      containers:
      - name: 'instance'
        image: '{{ image }}'
        command: [ "/bin/bash" ]
        args: [ "-c", "{{ args }}" ]
        imagePullPolicy: IfNotPresent     