apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ instanceLabel }}-{{ id }}'
  labels:
    app: '{{ app }}'
    {{ label }}/id: "{{ id }}"
spec:
  selector:
    matchLabels:
      app: '{{ app }}'
      instance: '{{ instanceLabel }}-{{ id }}'
  template:
    metadata:
      labels:
        app: '{{ app }}'
        instance: '{{ instanceLabel }}-{{ id }}'
    spec:
      terminationGracePeriodSeconds: 1
      hostNetwork: true
      nodeSelector:
        kubernetes.io/hostname: {{ hostname }}
      containers:
      - name: 'instance'
        image: '{{ image }}'
        command: [ "/bin/bash" ]
        args: [ "-c", "{{ args }}" ]
        imagePullPolicy: IfNotPresent
        env:
        - name: BOOKING_ID
          value: '{{ id }}'
        - name: GIT_REPO
          value: {{ gitRepo }}
        - name: GIT_KEY
          value: {{ gitKey }}